/**
 * Categories whose OpenAPI specs and api-reference pages this repo owns.
 *
 * These are the Legacy Unified APIs, moved here from the docs repo. The
 * remaining categories (documents, iam, stackone) stay in docs and are
 * regenerated by the equivalent script there.
 */
export const CATEGORIES = ['hris', 'ats', 'crm', 'lms', 'accounting'] as const;

export type Category = (typeof CATEGORIES)[number];
